swagger: "2.0"
info:
  description: "This is Runnning-ShrimpBurger's LoL-MBTI API document."
  version: "0.0.1"
  title: "LoL MBTI API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ejb0329@gmail.com"
basePath: "/"
tags:
- name: "champion"
  description: "API about champion info"
schemes:
- "https"
- "http"
paths:
  /mbti:
    post:
      tags:
      - "champion"
      summary: "Information of champion"
      description: "Return the name of champion and match champions with mbti according to the result."
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Answer of mbti test"
        required: true
        schema:
          $ref: "#/definitions/Answer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ChampInfo"
        "400":
          description: "request form error"

definitions:
  Answer:
    type: "object"
    properties:
      line:
        type: "string"
      response:
        type: "array"
        items:
          type: "integer"
        example: [1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0]
  ChampInfo:
    type: "object"
    properties:
      name:
        type: "string"
      mbti:
        type: "string"
      good_champ:
        type: "string"
      bad_champ:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"