name: Clinet CI(Build and Push Docker Image)

on:
  push:
    branches: [ client-prod ]
  pull_request:
    branches: [ client-prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ejb0329/mbti-client
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Client/Dockerfile
