name: Server CI(Build and Push Docker Image)

on:
  push:
    branches: [ server-prod ]
  pull_request:
    branches: [ server-prod ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check pwd
      run: pwd

    - name: ls
      run: ls

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ejb0329/mbti-server
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Server/src/Dockerfile